name: Build binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew --no-daemon -PpublishVersion="${GITHUB_REF_NAME:1}" build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: ./build/libs/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: libs

      - name: Publish artifact
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
        run: ./gradlew --no-daemon -PpublishVersion="${GITHUB_REF_NAME:1}" publish jreleaserFullRelease

      - name: Release
        uses: softprops/action-gh-release@v1