name: Build binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew --no-daemon -PpublishVersion="${GITHUB_REF_NAME:1}" build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: ./build/libs/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: libs

      - name: Publish artifact
        env:
          signing_keyId: ${{ secrets.SIGNING_KEYID }}
          signing_key: ${{ secrets.SIGNING_KEY }}
          signing_password: ${{ secrets.SIGNING_PASSWORD }}
          ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
          ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
        run: ./gradlew --no-daemon -PpublishVersion="${GITHUB_REF_NAME:1}" publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}